credentials:
  usernames:
  
    admin:
      email: 'admin@gmail.com'
      name: 'Admin'
      password: '$2b$12$LUAgQGjHEYUH6vlDeBvJh.yDy3Cdx4IJ1bpIEPXxFC4rntZGdZln6'
      subscription_valid_until: '2099-12-31'
    
    rhenderson:      
      email: 'rhenderson@gmail.com'
      name: 'Rebecca Henderson'
      password: '$2b$12$v3vcLNy2A5fsJRreQ/YNpePUuE/LPdjBk73Bv8qvJ3zhD/q3HeM5S'
      subscription_valid_until: '2025-07-31'

    demo_test_user:
      email: 'email@gmail.com'
      name: 'test_user'
      password: '&mWbD308_:'
      subscription_valid_until: '2025-07-15'

cookie:
  
  expiry_days: 30
  key: 'a4f5c6b7-d8e9-4f0a-1b2c-3d4e5f6a7b8c'
  name: 'cookie_destilador'
